os: linux
dist: trusty
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

branches:
  only:
    - master

before_script:
  # How to use APCu driver on Travis CI
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  # How to use MongoDB driver on Travis CI
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - php -m
  - php -i
  - composer install

script:
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit
  - php vendor/bin/phpbench run --report=default

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
