language: php

php:
- 5.5
- 5.6
- 7.0
- 7.1

branches:
  only:
  - master

before_script:
- composer install

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit

cache:
  directories:
  - vendor
