language: php
os: linux
dist: trusty
group: edge

php:
- 5.5
- 5.6
- 7.0
- 7.1

branches:
  only:
  - master

before_script:
# How to use APCu driver on Travis CI
- if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
# How to use MongoDB driver on Travis CI
- if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
- php -m
- php -i
- composer install

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit

cache:
  directories:
  - vendor
