language: php

php:
- 5.5
- 5.6
- 7.0
- 7.1

branches:
  only:
  - master

before_script:
# How to use APCu driver on Travis CI
- echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
# How to use MongoDB driver on Travis CI
- echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- php -m
- composer install

script:
- php vendor/bin/phpcs
- php vendor/bin/phpunit

cache:
  directories:
  - vendor
